version: "3.7"

services: 
  api:
    build: ./backend
    environment: 
      - CONNECTION_STRING=postgres://demo_user:demo_user@db/demo_db
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks: 
      - network-backend
      - network-frontend
  
  webapp:
    build: ./frontend
    environment: 
      - API_URL=http://api:3001/data
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-frontend
  
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_user
      POSTGRES_DB: demo_db
    volumes:
      - ./init_sql_scripts/:/docker-entrypoint-initdb.d
    networks:
      - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb-data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks: 
      - network-backend

networks:
  network-backend:
  network-frontend:
volumes: 
  mongodb_data: